### ISSUE TITLE
Begin HTML pagina

### ISSUE THREAD

**Issue by MuysTim** [Rrednas/projectKrekelSchool#12]
Een kleine html pagina zodat we al iets kunnen laten zien aan de klant

**Comment by Mj0lnir87** [comment]
Home/Index, Login/Log in, en AdminScreen zijn toegevoegd. Allemaal responsive etc.

**Comment by Rrednas** [comment]
View voor items en list view voor items toegevoegd en werkend 
dat is eind van dit issue me dunkt
