### ISSUE TITLE
klassendiagram aanmaken

### ISSUE THREAD

**Issue by Rrednas** [Rrednas/projectKrekelSchool#2]

**Comment by Rrednas** [comment]
voor een reden kan ik geen enkele associatie maken. die waren wel gelukt maar zijn verdwenen en nu kan ik deze niet meer op dezelfde manier toevoegen

**Comment by MuysTim** [comment]
Ik denk dat dit issue grotendeels is afgerond. Misschien dat er later nog een paar dingen moeten worden toegevoegd. Maar het ziet er al goed uit.

**Comment by Rrednas** [comment]
juist properties moeten toegevoegd worden maar dit is af
